name: Build Kitchen Timer

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller

      - name: Build EXE
        run: pyinstaller kitchenTimer.spec  # ← 英数字に変更！

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: kitchen-timer-exe
          path: dist/kitchenTimer/kitchenTimer.exe  # ← ここも合わせて変更！
